version: 2.0
jobs:
  build:
    working_directory: ~/ucp
    docker:
    - {image: 'circleci/node:14.17.0'}
    steps:
    - checkout
    - run: {name: update-npm, command: sudo npm install -g npm@latest}
    - restore_cache: {key: 'dependency-cache-{{ checksum "package-lock.json" }}'}
    - run:
        name: Check npm and node version
        command: |
          node --version
          npm --version
    - run: {name: install-npm, command: npm install}
    - save_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
        paths: [./node_modules]
    - run: {name: test, command: npm test}
    - setup_remote_docker: {version: 19.03.13}
    - run:
        name: Build test container
        command: |
          docker build -t "ucp:${CIRCLE_BUILD_NUM}" .
workflows:
  version: 2
  nightly:
    jobs: [build]