# This code is licensed from CircleCI to the user under the MIT license.
# See here for details: https://circleci.com/developer/orbs/licensing
version: 2.1
description: |
  copy files to S3 bucket and then create an Cloudfront invalidation
  on the distribution.
orbs:
  aws-s3: circleci/aws-s3@1.0.11
commands:
  copy-site:
    description: |
      copy contents of local dir to S3 bucket then invalidate cloudfront cache
    parameters:
      access-key:
        description: "AKIA2RJ5NHOGTXPKUCNE"
        type: string
      secret-key:
        description: "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"
        type: string
      to:
        description: "s3://catalago-aws-app'"
        type: string    
      from:
        description: "A local *directory* path to sync with S3"
        type: string    
      distribution-id:
        description: "Cloudfront Distribution Id for cache invalidation."
        type: string
    steps:
    - aws-s3/sync:
        from: << parameters.from >>
        to: << parameters.to >>
        aws-access-key-id: << parameters.access-key >>
        aws-secret-access-key: << parameters.secret-key >>
        arguments: |
          --delete
    - run:
        name: "Invalidate CloudFront Cache"
        command: |
          aws cloudfront create-invalidation --distribution-id << parameters.distribution-id >> --paths "/*"